name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check for filenames with numbers
        run: |
          FILES_WITH_NUMBERS=$(find . -type f | grep -E '[0-9]')
          if [ -n "$FILES_WITH_NUMBERS" ]; then
            echo "❌ Error: The following files contain numbers in their names:"
            echo "$FILES_WITH_NUMBERS"
            exit 1
          else
            echo "✅ No filenames contain numbers."
          fi

      - name: List files in the repository
        run: ls -R

      - run: echo "🍏 This job's status is ${{ job.status }}."
