name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check for uppercase file names
        run: |
          if find ${{ github.workspace }} -type f | grep -q '[A-Z]'; then
            echo "❌ Error: Some files have uppercase letters!"
            find ${{ github.workspace }} -type f | grep '[A-Z]'
            exit 1
          else
            echo "✅ All file names are lowercase."
          fi

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
